const Main = async () => {
    try {
       
        



        
    } catch (error) {
       console.log(error); 
    }
    process.exit();
}

main();